FROM r-base:3.4.0

RUN apt-get update &&\
    apt-get install -y --no-install-recommends libssl-dev\
    libssh2-1-dev libcurl4-openssl-dev pandoc libxml2-dev

ADD . /CEMiTool

WORKDIR /CEMiTool

RUN Rscript docker/install-deps.R
